---
title: "final project"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
install.packages('plyr', repos = "http://cran.us.r-project.org")
library(gamlr)
```

```{r project}
library("dplyr")
library("lubridate")
library("cobalt")
library("jtools")
library("kableExtra")
library("stargazer")
###################################################################################

covid <- read.csv("United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv")
covid_AZ <- covid[covid$state == "AZ",]
covid_NV <- covid[covid$state == "NV",]

#as.numeric(as.character(covid_AZ$pop))
covid_AZ$tot_cases_pop <- round(as.numeric(as.character(covid_AZ$tot_cases))/7276316, digits = 2)*100
covid_AZ$tot_death_pop <- round(as.numeric(as.character(covid_AZ$tot_death))/7276316, digits = 4)*100

covid_NV$tot_cases_pop <- round(as.numeric(as.character(covid_NV$tot_cases))/3143991, digits = 2)*100
covid_NV$tot_death_pop <- round(as.numeric(as.character(covid_NV$tot_death))/3143991, digits = 4)*100

covid_AZ_NV <- union(covid_AZ, covid_NV)

# setting up for time series for AZ and NV June 26, 2020 mask mandate 
covid_AZ_NV$submission_date <- lubridate::mdy(covid_AZ_NV$submission_date)
covid_AZ_NV <- dplyr::arrange(covid_AZ_NV, submission_date)

# making treatment
covid_AZ_NV$after <- ifelse(covid_AZ_NV$submission_date >= "2020-06-26", 1, 0)
covid_AZ_NV$treat <- ifelse(covid_AZ_NV$state == "NV", 1, 0)

# diff in diff
AZ_NV_didreg_tot_death_pop <- glm(tot_death_pop ~ treat + after + after*treat, data = covid_AZ_NV)
summary(AZ_NV_didreg_tot_death_pop, robust = TRUE)
summ(AZ_NV_didreg_tot_death_pop, robust = TRUE)
stargazer(AZ_NV_didreg_tot_death_pop)

AZ_NV_didreg_tot_cases_pop <- glm(tot_cases_pop ~ treat + after + after*treat, data = covid_AZ_NV)
summary(AZ_NV_didreg_tot_cases_pop, robust = TRUE)
summ(AZ_NV_didreg_tot_cases_pop, robust = TRUE)

# plot
xseq<-seq.Date(min(covid_AZ_NV$submission_date),max(covid_AZ_NV$submission_date),by='1 months') 
yseq<-round(seq(0,max(covid_AZ_NV$tot_cases_pop),by=1),0)

covid_AZ_NV$submission_date <- as.Date(covid_AZ_NV$submission_date)
plot(covid_AZ_NV$tot_cases_pop[covid_AZ_NV$treat == 1]~covid_AZ_NV$submission_date[covid_AZ_NV$treat == 1],
     type='o', ylim=c(0,max(covid_AZ_NV$tot_cases_pop)),
     xlim=c(min(covid_AZ_NV$submission_date), max(covid_AZ_NV$submission_date)), axes=F, col = "red", xlab = "Dates", 
     main = "COVID-19 Total Case divide by Population Time Series", ylab = "COVID-19 Total Case");box() 
axis.Date(side=1,at=xseq, format='%y-%m', labels=T,las=3)
axis(side=2,at=yseq,las=2)
points(covid_AZ_NV$tot_cases_pop[covid_AZ_NV$treat == 0]~covid_AZ_NV$submission_date[covid_AZ_NV$treat == 0], type='o',col = "blue")
abline(v = as.Date("2020-06-26"), lwd=2, lty=2)

###################################################################################

# Economic data AZ and NV unemployment
# Links: https://fred.stlouisfed.org/series/AZUR
# Links: https://fred.stlouisfed.org/series/NVUR
AZ_UP <- read.csv("AZUR.csv")
AZ_UP$UR <- AZ_UP$AZUR
AZ_UP$state <- "AZ"
AZ_UP <- subset(AZ_UP, select = -AZUR)

NV_UP <- read.csv("NVUR.csv")
NV_UP$UR <- NV_UP$NVUR
NV_UP$state <- "NV"
NV_UP <- subset(NV_UP, select = -NVUR)

AZ_NV_UP <- union(AZ_UP, NV_UP)

# setting up for time series for AZ and NV June 26, 2020 mask mandate 
AZ_NV_UP$DATE <- lubridate::ymd(AZ_NV_UP$DATE)
AZ_NV_UP <- dplyr::arrange(AZ_NV_UP, DATE)

# making treatment
AZ_NV_UP$after <- ifelse(AZ_NV_UP$DATE >= "2020-07-01", 1, 0)
AZ_NV_UP$treat <- ifelse(AZ_NV_UP$state == "NV", 1, 0)

# diff in diff
AZ_NV_UP_didreg <- glm(AZ_NV_UP$UR ~ AZ_NV_UP$treat + AZ_NV_UP$after + AZ_NV_UP$after*AZ_NV_UP$treat)
summary(AZ_NV_UP_didreg)

# Plot
xseq<-seq.Date(min(AZ_NV_UP$DATE),max(AZ_NV_UP$DATE),by='1 months') 
yseq<-round(seq(0,max(AZ_NV_UP$UR),by=1),0)

plot(AZ_NV_UP$UR[AZ_NV_UP$treat==1]~AZ_NV_UP$DATE[AZ_NV_UP$treat==1], 
     type='b', ylim=c(0,max(AZ_NV_UP$UR)),
     xlim=c(min(AZ_NV_UP$DATE), max(AZ_NV_UP$DATE)), axes=F,
     col = "red", xlab = "Date", main = "Unemployment rate Time Series", ylab = "Unemployment rate");box() 
axis.Date(side=1,at=xseq, format='%y-%m', labels=T,las=3)
axis(side=2,at=yseq,las=2)
points( AZ_NV_UP$UR[AZ_NV_UP$treat==0]~AZ_NV_UP$DATE[AZ_NV_UP$treat==0], type='b', col = "blue")
abline(v = as.Date("2020-07-01"), lwd=2, lty=2)

#######################################################################################################################
# Economic data AZ and NV Labor Force Participation Rate 
# Links: https://fred.stlouisfed.org/series/LBSNSA32
# Links: https://fred.stlouisfed.org/series/LBSSA04
AZ_LFPR <- read.csv("LBSSA04.csv")
AZ_LFPR$LFPR <- AZ_LFPR$LBSSA04
AZ_LFPR$state <- "AZ"
AZ_LFPR <- subset(AZ_LFPR, select = -LBSSA04)

NV_LFPR <- read.csv("LBSNSA32.csv")
NV_LFPR$LFPR <- NV_LFPR$LBSNSA32
NV_LFPR$state <- "NV"
NV_LFPR <- subset(NV_LFPR, select = -LBSNSA32)

AZ_NV_LFPR <- union(AZ_LFPR, NV_LFPR)

# setting up for time series for AZ and NV June 26, 2020 mask mandate 
AZ_NV_LFPR$DATE <- lubridate::ymd(AZ_NV_LFPR$DATE)
AZ_NV_LFPR <- dplyr::arrange(AZ_NV_LFPR, DATE)

# making treatment
AZ_NV_LFPR$after <- ifelse(AZ_NV_LFPR$DATE >= "2020-07-01", 1, 0)
AZ_NV_LFPR$treat <- ifelse(AZ_NV_LFPR$state == "NV", 1, 0)


# diff in diff
AZ_NV_LFPR_didreg <- glm(AZ_NV_LFPR$LFPR ~ AZ_NV_LFPR$treat + AZ_NV_LFPR$after + AZ_NV_LFPR$after*AZ_NV_LFPR$treat)
summary(AZ_NV_LFPR_didreg)

# Plot
xseq<-seq.Date(min(AZ_NV_LFPR$DATE),max(AZ_NV_LFPR$DATE),by='1 months') 
yseq<-round(seq(min(AZ_NV_LFPR$LFPR),max(AZ_NV_LFPR$LFPR),by=1),0)

plot(AZ_NV_LFPR$LFPR[AZ_NV_LFPR$treat==1]~AZ_NV_LFPR$DATE[AZ_NV_LFPR$treat==1],
     type='b', ylim=c(min(AZ_NV_LFPR$LFPR), max(AZ_NV_LFPR$LFPR)),
     xlim=c(min(AZ_NV_LFPR$DATE), max(AZ_NV_LFPR$DATE)), axes=F,
     col = "red", xlab = "Date", main = "Labor Force Participation Rate  Time Series", ylab = "Labor Force Participation Rate");box() 
axis.Date(side=1,at=xseq, format='%y-%m', labels=T,las=3)
axis(side=2,at=yseq,las=2)
points(AZ_NV_LFPR$LFPR[AZ_NV_LFPR$treat==0]~AZ_NV_LFPR$DATE[AZ_NV_LFPR$treat==0],type='b', col = "blue")
abline(v = as.Date("2020-07-01"), lwd=2, lty=2)

#####################################################################################################################  
# Balance Table for COVID-19 case
covid_AZ_NV_1 <- data.frame(covid_AZ_NV$submission_date, covid_AZ_NV$tot_cases, covid_AZ_NV$tot_death, covid_AZ_NV$after, covid_AZ_NV$treat)
covid_AZ_NV_1 <- covid_AZ_NV_1[1:314,]
bal.tab(covid_AZ_NV_1, treat = covid_AZ_NV_1$covid_AZ_NV.treat, disp = c("diff", "means", "sds"))

# Balance Table for Unemployment 
AZ_NV_UP <- AZ_NV_UP[1:60,]
bal.tab(AZ_NV_UP, treat = AZ_NV_UP$treat, disp = c("diff", "means", "sds"))

# Balance Table for Labor Force Participation Rate
AZ_NV_LFPR <- AZ_NV_LFPR[1:60,]
bal.tab(AZ_NV_LFPR, treat = AZ_NV_LFPR$treat, disp = c("diff", "means", "sds"))

```
